# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: educacion
  username: cec
  password: educacion
  host: 192.168.26.104
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: educacion
  username: cec
  password: educacion
  host: 192.168.26.104
  port: 3306

production:
  adapter: postgresql
  database: educacion
  pool: 5
  timeout: 5000